<?php

namespace Advaith\SeamlessAdmin\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Cache;

class ClearCache extends Command
{
    protected $signature = 'seamless:clear';

    protected $description = 'Clear models cache generated by the seamless admin package';

    public function handle()
    {
        Cache::forget(app('modelResolver')->getCacheKey());

        $this->info('Cleared models cache!');
    }
}
